version: "3.9"
services:
  nginx:
    container_name: test-server
    build:
      context: ${CONTEXT}
      dockerfile: Dockerfile
    tty: true
    ports: 
      - "80:80"
    volumes:
      - ${CONTEXT}:/usr/share/nginx/html
    networks:
      - default

networks:
  default:
    name: ${NETWORK}
